/* ============================================================
   admin/helpdesk.js — help-request inbox, replies, and resolution
   ============================================================ */
(function () {
  "use strict";
  const $ = (selector, root = document) => root.querySelector(selector); const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));  const State = { admin: null, filter: "Open", tickets: new Map(), bound: false, listening: false, selected: null };
  const previousInit = window.AdminShared?.initFilters; window.AdminShared = window.AdminShared || {}; window.AdminShared.initFilters = function (state) { previousInit?.(state); State.admin = state.admin; attachFilters(); listen(); };
  function escape(value) { return ClassCareUI.escapeHtml(value); }
  function attachFilters() { if (State.bound) return; State.bound = true; $$("#tab-helpdesk [data-filter]").forEach(button => button.addEventListener("click", () => { State.filter = button.dataset.filter; $$("#tab-helpdesk [data-filter]").forEach(item => item.classList.toggle("active", item === button)); render(); })); }
  function listen() { if (State.listening) return; State.listening = true; try { ClassCare.DB.helpdesk_tickets.orderBy("timestamp", "desc").limit(200).onSnapshot(snapshot => { snapshot.docChanges().forEach(change => { const ticket = { id: change.doc.id, ...change.doc.data() }; if (change.type === "removed") State.tickets.delete(ticket.id); else State.tickets.set(ticket.id, ticket); }); render(); updateTicketCount(); }, error => { console.warn("[helpdesk] listener failed:", error); renderError("Help requests unavailable", "Check your connection and try again."); }); } catch (error) { renderError("Help requests unavailable", "Check your connection and try again."); } }
  function updateTicketCount() { const count = Array.from(State.tickets.values()).filter(ticket => ticket.status === "Open").length; const stat = $("#stat-tickets"); if (stat) stat.textContent = String(count); }
  function renderError(title, message) { const list = $("#helpdesk-list"); if (list) list.innerHTML = `<div class="state-panel state-error"><strong>${escape(title)}</strong><span>${escape(message)}</span></div>`; }
  function render() { const list = $("#helpdesk-list"); if (!list) return; const tickets = Array.from(State.tickets.values()).filter(ticket => !State.filter || ticket.status === State.filter).sort((a, b) => (b.timestamp?.toDate?.()?.getTime?.() || 0) - (a.timestamp?.toDate?.()?.getTime?.() || 0)); if (!tickets.length) { list.innerHTML = `<div class="state-panel state-empty"><strong>${State.filter === "Open" ? "There are no open help requests." : "No help requests match this filter."}</strong><span>New student requests will appear here.</span></div>`; $("#helpdesk-detail")?.classList.add("hidden"); return; } list.innerHTML = tickets.map(ticket => { const when = ticket.timestamp?.toDate?.() ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(ticket.timestamp.toDate()) : "—"; const selected = State.selected === ticket.id ? " is-selected" : ""; return `<button type="button" class="inbox-row${selected}" data-ticket-id="${escape(ticket.id).replace(/"/g, "&quot;")}"><span><span class="inbox-name">${escape(ticket.sender_name || "Student")}</span><span class="inbox-meta">${escape(ticket.sender_id || "No ID")} · ${escape(ticket.section || "No section")} · ${escape(when)}</span><span class="inbox-excerpt">${escape(ticket.message || "No message")}</span></span>${ClassCareUI.statusBadge(ticket.status === "Open" ? "Late" : "Present", ticket.status)}</button>`; }).join(""); list.querySelectorAll("[data-ticket-id]").forEach(button => button.addEventListener("click", () => selectTicket(button.dataset.ticketId))); if (State.selected) renderDetail(); }
  function selectTicket(id) { State.selected = id; render(); renderDetail(); }
  function renderDetail() { const detail = $("#helpdesk-detail"); const ticket = State.tickets.get(State.selected); if (!detail || !ticket) return detail?.classList.add("hidden"); detail.classList.remove("hidden"); detail.innerHTML = `<div class="modal-header"><div><h3>${escape(ticket.sender_name || "Student")}</h3><p class="modal-copy">${escape(ticket.sender_id || "No ID")} · ${escape(ticket.section || "No section")}</p></div><span>${ClassCareUI.statusBadge(ticket.status === "Open" ? "Late" : "Present", ticket.status)}</span></div><p class="detail-panel-copy">${escape(ticket.message || "No message")}</p>${ticket.admin_reply ? `<div class="detail-panel-copy"><strong>Previous reply</strong><br />${escape(ticket.admin_reply)}</div>` : ""}<form id="ticket-reply-form" class="form-stack"><div><label class="field-label" for="ticket-reply">Reply to student</label><textarea id="ticket-reply" name="reply" class="field" rows="4" placeholder="Write a clear next step."></textarea></div><div class="form-actions">${ticket.status === "Open" ? `<button class="btn btn-secondary" type="button" id="ticket-resolve">Mark resolved</button>` : ""}<button class="btn btn-primary" type="submit" id="ticket-send">Send reply</button></div></form>`; $("#ticket-reply-form")?.addEventListener("submit", event => { event.preventDefault(); const reply = Utils.sanitizeText(new FormData(event.target).get("reply"), { max: 1000 }); if (!reply) return Toast.warn("Write a reply before sending."); sendReply(ticket, reply); }); $("#ticket-resolve")?.addEventListener("click", () => markResolved(ticket)); }
  async function sendReply(ticket, reply) { const button = $("#ticket-send"); Utils.setLoading(button, true); try { const admin = State.admin; await ClassCare.DB.helpdesk_tickets.doc(ticket.id).update({ admin_reply: reply, admin_reply_by_uid: admin.uid, admin_reply_by_name: `${admin.first_name || ""} ${admin.last_name || ""}`.trim(), admin_reply_at: firebase.firestore.FieldValue.serverTimestamp() }); if (ticket.sender_uid && window.TelegramAlert) { const student = await ClassCare.DB.users.doc(ticket.sender_uid).get(); if (student.exists) { const result = await TelegramAlert.sendText(student.data(), reply); Toast.info(result.ok ? "Reply sent and parent notified." : result.queued ? "Reply sent. Parent notification is queued." : "Reply sent. Parent notification is not configured."); } } else Toast.success("Reply sent to the student."); } catch (error) { console.error("[helpdesk] reply failed:", error); Toast.error(error?.code === "permission-denied" ? "You do not have permission to reply." : "Reply could not be sent. Keep the text and try again."); const textarea = $("#ticket-reply"); if (textarea) textarea.value = reply; } finally { Utils.setLoading(button, false); } }
  async function markResolved(ticket) { try { await ClassCare.DB.helpdesk_tickets.doc(ticket.id).update({ status: "Resolved", resolved_at: firebase.firestore.FieldValue.serverTimestamp(), resolved_by_uid: State.admin.uid }); State.selected = null; Toast.success("Help request marked resolved."); } catch (error) { console.error("[helpdesk] resolve failed:", error); Toast.error("The help request could not be updated."); } }
})();
